# Generated by Django 5.0.3 on 2024-03-12 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0003_rename_target_muscle_exercise_target_muscles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetition', models.PositiveIntegerField()),
                ('set', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField()),
                ('exercise', models.ManyToManyField(to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
