# Generated by Django 5.0.3 on 2024-03-09 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desctiption', models.TextField()),
                ('instruction', models.TextField()),
                ('target_muscle', models.CharField(choices=[('legs', 'legs'), ('chest', 'chest'), ('abs', 'abs'), ('biceps', 'biceps'), ('triceps', 'triceps')], max_length=10)),
            ],
        ),
    ]
