# Generated by Django 5.0.3 on 2024-03-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='desctiption',
            new_name='description',
        ),
    ]
