# Generated by Django 5.0.3 on 2024-03-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_rename_desctiption_exercise_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='target_muscle',
            new_name='target_muscles',
        ),
    ]
